object Versions {
    const val android = "7.3.1"
    const val coroutines = "1.6.4"
    const val viewModel = "2.5.1"
    const val coreKtx = "1.7.20"
    const val kotlin = "1.7.20"
    const val espresso = "3.5.1"
    const val junit = "4.13.2"
    const val junitTest = "1.1.5"
    const val material = "1.3.1"
    const val appCompat = "1.5.1"
    const val composeBom = "2022.12.00"
    const val lifecycleRuntime = "2.5.1"
    const val coil = "2.2.2"
    const val accompanist = "0.28.0"
    const val compose = "1.3.2"
    const val composeTooling = "1.3.3"
    const val hiltCompose = "1.0.0"
    const val destination = "1.7.32-beta"
    const val accompanistSystUiController = "0.29.0-alpha"
    const val hilt = "2.44"
    const val composeActivity = "1.6.1"
    const val composeLifecycleViewModel = "2.5.1"
    const val dataStore = "1.0.0"
}

